FROM debian:trixie

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    gcc \
    gnat \
    gprbuild \
    libc6-dev \
    tar \
    unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work

CMD ["/bin/sh"]
